FROM ddm501-t02-mlflow:2.19.0

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /work

RUN pip install --no-cache-dir \
    "psycopg2-binary==2.9.10" \
    "boto3==1.35.90"

COPY scripts/ ./scripts/

CMD ["mlflow", "--version"]
